# Generated by Django 4.2.14 on 2024-07-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_name', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.IntegerField()),
                ('additional_info', models.CharField(max_length=200)),
            ],
        ),
    ]
