# Generated by Django 4.2.14 on 2024-08-16 18:59

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='image'),
        ),
    ]
