# Generated by Django 4.2.14 on 2024-07-30 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='bird',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
