# Generated by Django 4.2.14 on 2025-04-25 20:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="main_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
