# Generated by Django 4.2.14 on 2024-08-16 19:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0002_alter_bird_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
