# Generated by Django 4.2.14 on 2024-07-30 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bird_tracker', '0002_alter_bird_options_bird_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField()),
                ('food_type', models.CharField(max_length=12)),
                ('food_weight', models.IntegerField()),
                ('Weather', models.IntegerField(choices=[(0, 'Rainy'), (1, 'Sunny'), (2, 'Windy'), (3, 'Cold')], default=1)),
                ('Temp', models.IntegerField()),
                ('Training', models.IntegerField(choices=[(0, 'Featherplay'), (1, 'Faustappel')], default=0)),
                ('behaviour', models.IntegerField(choices=[(0, 'Motivated'), (1, 'Reticent')], default=0)),
                ('selected_bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_bird', to='bird_tracker.bird')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
