# Generated by Django 4.2.14 on 2024-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0003_daily_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily_data',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='bird',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
