# Generated by Django 4.2.14 on 2025-11-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0003_alter_bird_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailydata",
            name="food_time",
            field=models.CharField(default="15h00", max_length=6),
        ),
        migrations.AlterField(
            model_name="bird",
            name="date_of_birth",
            field=models.CharField(default="Unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="bird",
            name="sex",
            field=models.IntegerField(
                choices=[(0, "Female"), (1, "Male"), (2, "Unknown")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="behaviour",
            field=models.IntegerField(
                choices=[
                    (0, "Motivated"),
                    (1, "Lethargic"),
                    (2, "Aggressive"),
                    (3, "Unmotivated"),
                    (4, "Slightly Unmotivated"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="training",
            field=models.IntegerField(
                choices=[
                    (0, "No Training"),
                    (1, "Faustappel"),
                    (2, "Free Flight"),
                    (3, "Feather Play"),
                ],
                default=0,
            ),
        ),
    ]
