# Generated by Django 4.2.14 on 2025-11-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0004_dailydata_food_time_alter_bird_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailydata",
            name="training_time",
            field=models.CharField(default="11h00", max_length=6),
        ),
    ]
