# Generated by Django 4.2.14 on 2024-07-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0004_alter_daily_data_options_alter_bird_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_data',
            old_name='Temp',
            new_name='temp',
        ),
        migrations.RenameField(
            model_name='daily_data',
            old_name='Training',
            new_name='training',
        ),
        migrations.RenameField(
            model_name='daily_data',
            old_name='Weather',
            new_name='weather',
        ),
    ]
