# Generated by Django 4.2.14 on 2025-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0005_dailydata_training_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="training_time",
            field=models.CharField(max_length=6),
        ),
    ]
