# Generated by Django 4.2.14 on 2024-08-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0005_rename_temp_daily_data_temp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_data',
            old_name='temp',
            new_name='temperature',
        ),
    ]
