# Generated by Django 4.2.14 on 2024-08-03 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bird_tracker', '0006_rename_temp_daily_data_temperature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_data',
            new_name='DailyData',
        ),
    ]
