# Generated by Django 4.2.14 on 2025-11-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0006_alter_dailydata_training_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="training_time",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
