# Generated by Django 4.2.14 on 2025-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0007_alter_dailydata_training_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="behaviour",
            field=models.IntegerField(
                choices=[
                    (0, "Motivated"),
                    (1, "Lethargic"),
                    (2, "Aggressive"),
                    (3, "Unmotivated"),
                    (4, "Slightly Unmotivated"),
                    (5, "Neutral"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
