# Generated by Django 4.2.14 on 2024-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0007_rename_daily_data_dailydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='food_weight',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
