# Generated by Django 4.2.14 on 2025-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0008_alter_dailydata_behaviour_alter_dailydata_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="training",
            field=models.IntegerField(
                choices=[
                    (0, "No Training"),
                    (1, "Faustappel"),
                    (2, "Free Flight"),
                    (3, "Lure Play"),
                ],
                default=0,
            ),
        ),
    ]
