# Generated by Django 4.2.14 on 2024-08-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0008_alter_dailydata_food_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='weight',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
