# Generated by Django 4.2.14 on 2025-12-07 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0009_alter_dailydata_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailydata",
            name="training_motivation",
            field=models.IntegerField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
