# Generated by Django 4.2.14 on 2024-08-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0010_alter_dailydata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='date',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
