# Generated by Django 4.2.14 on 2025-12-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0010_alter_dailydata_training"),
        ("bird_tracker", "0011_alter_dailydata_training_motivation"),
    ]

    operations = []
