# Generated by Django 4.2.14 on 2025-12-08 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0012_merge_20251208_1533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="training_motivation",
            field=models.IntegerField(
                blank=True,
                default="",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
