# Generated by Django 4.2.14 on 2024-08-09 17:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0013_alter_dailydata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='training',
            field=models.IntegerField(choices=[(0, 'Featherplay'), (1, 'Faustappel'), (2, 'Free Flight')], default=0),
        ),
    ]
