# Generated by Django 4.2.14 on 2024-08-09 17:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_tracker', '0014_bird_main_image_alter_dailydata_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='notable_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='notable_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
