# Generated by Django 4.2.14 on 2025-12-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0012_merge_20251208_1454"),
        ("bird_tracker", "0014_alter_dailydata_training_motivation"),
    ]

    operations = []
