# Generated by Django 4.2.14 on 2025-12-15 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0015_merge_20251215_2008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
