# Generated by Django 4.2.14 on 2025-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0016_alter_dailydata_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="training_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
