# Generated by Django 4.2.14 on 2025-12-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0017_alter_dailydata_training_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="food_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
