# Generated by Django 4.2.14 on 2025-12-16 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0018_alter_dailydata_food_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="temperature",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(-50),
                    django.core.validators.MaxValueValidator(50),
                ]
            ),
        ),
    ]
