# Generated by Django 4.2.14 on 2025-12-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0015_merge_20251217_1636"),
        ("bird_tracker", "0019_alter_dailydata_temperature"),
    ]

    operations = []
