# Generated by Django 4.2.14 on 2025-12-19 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0020_merge_20251218_2241"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="target_weight",
            field=models.PositiveSmallIntegerField(
                default=350,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
            ),
        ),
    ]
