# Generated by Django 4.2.14 on 2025-12-19 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0023_alter_bird_target_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="target_weight",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20000),
                ],
            ),
        ),
    ]
