# Generated by Django 4.2.14 on 2025-12-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0020_merge_20251217_1748"),
        ("bird_tracker", "0024_alter_bird_target_weight"),
    ]

    operations = []
