# Generated by Django 4.2.14 on 2026-03-03 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0025_merge_20251220_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="behaviour",
            field=models.IntegerField(
                choices=[
                    (0, "Motivated"),
                    (1, "Lethargic"),
                    (2, "Aggressive"),
                    (3, "Unmotivated"),
                    (4, "Slightly Unmotivated"),
                    (5, "Neutral"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="food_weight",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="temperature",
            field=models.IntegerField(
                blank=True,
                default=15,
                validators=[
                    django.core.validators.MinValueValidator(-50),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="training",
            field=models.IntegerField(
                choices=[
                    (0, "No Training"),
                    (1, "Faustappel"),
                    (2, "Free Flight"),
                    (3, "Lure Flying"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="weather",
            field=models.IntegerField(
                choices=[
                    (0, "Rainy"),
                    (1, "Sunny"),
                    (2, "Windy"),
                    (3, "Cold"),
                    (4, "Not Given"),
                ],
                default=4,
                null=True,
            ),
        ),
    ]
