# Generated by Django 4.2.14 on 2026-03-03 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0026_alter_dailydata_behaviour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="temperature",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-50),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]
