# Generated by Django 4.2.14 on 2026-03-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0027_alter_dailydata_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="food_weight",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
