# Generated by Django 4.2.14 on 2026-03-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0028_alter_dailydata_food_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="training",
            field=models.IntegerField(
                choices=[
                    (0, "No Training"),
                    (1, "Faustappel"),
                    (2, "Free Flight"),
                    (3, "Lure Flying"),
                    (4, "Hunting"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="weather",
            field=models.IntegerField(
                choices=[
                    (0, "Rainy"),
                    (1, "Sunny"),
                    (2, "Windy"),
                    (3, "Cold"),
                    (4, "--"),
                ],
                default=4,
                null=True,
            ),
        ),
    ]
