# Generated by Django 4.2.14 on 2026-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0029_alter_dailydata_training_alter_dailydata_weather"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailydata",
            name="food_type",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="dailydata",
            name="weight",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
