# Generated by Django 4.2.14 on 2026-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird_tracker", "0030_alter_dailydata_food_type_alter_dailydata_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
